config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :sessions, only: [:new, :create]
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :places, only: [:index, :show] do
    resources :recomendations, only: [:create] do
      get 'tweet', to: 'recomendations#tweet'
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :recomendations
end

app/models/recomendation.rb
class Recomendation < ApplicationRecord
  belongs_to :user
  belongs_to :place  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :accounts, dependent: :destroy
  has_many :recomendations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  
  def authenticated_only
    redirect_to places_path unless current_user
  end

  def current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  before_action :find_place, only: [:show]

  def index
    @places = Place.all
    @recomendation = Recomendation.new
  end

  def show
  end

  private

  def find_place
    @place = Place.find(params[:id])
  end
end

app/controllers/recomendations_controller.rb
class RecomendationsController < ApplicationController
  
  before_action :authenticated_only
  
  def create
    recomendation = current_user.recomendations.new(recomendation_params)
    if recomendation.save
      flash[:notice] = "Recomendation successfuly add to place"
      redirect_to places_path
    else 
      flash[:alert] = "Recomendation not add to place"
      redirect_to places_path
    end
  end


  def tweet
    place = Place.find(params[:place_id])
    recomendation = Recomendation.find(params[:recomendation_id])
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['tw_api_key']
      config.consumer_secret     = ENV['tw_api_secret']
      config.access_token        = current_user.token
      config.access_token_secret = current_user.token_secret
    end
    client.update("I leave recomendation to #{place.name} \n #{recomendation.text}\n"\
                  "and i give a mark #{recomendation.point}!\nhttp://localhost:3000/places")
    redirect_to :back
  end

  private 

  def recomendation_params
    params.require(:recomendation).permit(:text, :point).merge(place_id: params[:place_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @account = Account.find_by(account_params)
    unless @account
      @account = Account.create(account_params)
      @account.update(user_id: user_params.id)
    end
    session[:user_id] = @account.user_id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def auth_params
    request.env['omniauth.auth']
  end

  def account_params
    {
      uid: auth_params['uid'],
      provider: auth_params['provider']
    }
  end

  def user_params
    User.find_or_create_by(email: auth_params['info']['nickname'], 
                           token: auth_params["credentials"]["token"],
                           token_secret: auth_params["credentials"]["secret"] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/recomendatons_helper.rb
module RecomendatonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeekHubExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "sessions/new" %>
    <%= yield %>
  </body>
</html>

app/views/places/index.slim
.container
  - if flash[:notice] 
    .notice = flash[:notice]
  - if flash[:alert] 
    .alert = flash[:alert]

  h2 Places
  table.table
    thead
      tr
        th Name
        th Recomendations
        th Add recomendation
    - @places.each do |place|
      tbody
        tr
          td = place.name
          td = place.recomendations.count  
          - if current_user
            td 
              button.btn.btn-info.btn-sm data-target="#myModal" data-toggle="modal" type="button" Add recomendation
            td = link_to "Show place", place_path(place.id), class: "btn btn-info"
          - else 
            td authenticated only

        /! Modal
        #myModal.modal.fade role="dialog" 
          .modal-dialog
            /! Modal content
            .modal-content
              .modal-header
                button.close data-dismiss="modal" type="button"  &times;
                h4.modal-title Add recomendation
              .modal-body
                = form_for [place, @recomendation] do |f|
                  .form-group
                    = f.label "Recomendation text"
                    = f.text_area :text, class: "form-control", required: true
                  .form-group
                    = f.label "points"
                    = f.number_field :point, min: 1, max: 5, class: "form-control", required: true
                  = f.submit "Submit", class: "btn btn-primary" 
              .modal-footer
                button.btn.btn-default data-dismiss="modal" type="button"  Close

app/views/places/show.slim
h1 Place name #{@place.name}

h3 All Recomentadions
table.table
  thead
    tr
      th Author
      th Text
      th Points
  - @place.recomendations.each do |recomendation|
    tbody
      tr
        td = recomendation.user.email
        td = recomendation.text
        td = recomendation.point
        td = link_to "Tweet", place_recomendation_tweet_path(@place.id, recomendation.id), method: :post 